name: Build all wheels
on: create

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "3.6"
            os: "ubuntu-latest"
            start_worker: "docker run -di -v ${WORKSPACE}:${WORKSPACE} -w ${WORKSPACE} --name worker --rm quay.io/pypa/manylinux2010_x86_64"
            worker: "docker exec worker"
            stop_worker: "docker kill worker"
          - name: "3.7"
            os: "ubuntu-latest"
            start_worker: "docker run -di -v ${WORKSPACE}:${WORKSPACE} -w ${WORKSPACE} --name worker --rm quay.io/pypa/manylinux2010_x86_64"
            worker: "docker exec worker"
            stop_worker: "docker kill worker"
          - name: "3.8"
            os: "ubuntu-latest"
            start_worker: "docker run -di -v ${WORKSPACE}:${WORKSPACE} -w ${WORKSPACE} --name worker --rm quay.io/pypa/manylinux2010_x86_64"
            worker: "docker exec worker"
            stop_worker: "docker kill worker"
          - name: "3.9"
            os: "ubuntu-latest"
            start_worker: "docker run -di -v ${WORKSPACE}:${WORKSPACE} -w ${WORKSPACE} --name worker --rm quay.io/pypa/manylinux2010_x86_64"
            worker: "docker exec worker"
            stop_worker: "docker kill worker"
          - name: "3.6"
            os: "macos-latest"
          - name: "3.7"
            os: "macos-latest"
          - name: "3.8"
            os: "macos-latest"
          - name: "3.9"
            os: "macos-latest"
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.9"
      WORKSPACE: "${{ github.workspace }}"
    steps:
      - name: Checkout latest revision
        uses: actions/checkout@v2
        with:
          repository: lamyj/sycomore
          fetch-depth: 0
      - name: Start the worker
        run: ${{ matrix.start_worker }}
      - name: Configure Python interpreter
        run: |
          PYTHON_ROOT=$(python3 ./.ci/wheels/setup_python.py '${{ matrix.name }}' | tail -n 1)
          echo "PYTHON_ROOT=$PYTHON_ROOT" >> $GITHUB_ENV
      - name: Provision
        run: |
          ${{ matrix.worker }} ./.ci/wheels/provision.sh
          ${{ matrix.worker }} $PYTHON_ROOT/python -m pip install --force-reinstall pip
          ${{ matrix.worker }} $PYTHON_ROOT/python -m pip install setuptools wheel setuptools_scm
      - name: Build wheel
        run: |
          ${{ matrix.worker }} $PYTHON_ROOT/python setup.py bdist_wheel
      - name: Test wheel
        run: |
          ${{ matrix.worker }} $PYTHON_ROOT/python -m pip install dist/*whl
          ${{ matrix.worker }} $PYTHON_ROOT/python -c 'import sycomore; sycomore.gamma'
      - name: Stop the worker
        run: ${{ matrix.stop_worker }}
      - name: Archive wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist/*whl
